//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa_pro_chefe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dados_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dados_cliente()
        {
            this.entregas = new HashSet<entregas>();
        }
    
        public int id { get; set; }
        public string cpf { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public string cep { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public int tipo_usuario { get; set; }
    
        public virtual tipo_usuario tipo_usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entregas> entregas { get; set; }
    }
}
