//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa_pro_chefe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dados_pedido
    {
        public int id { get; set; }
        public string observacoes { get; set; }
        public string borda { get; set; }
        public string preco_borda { get; set; }
        public string tamanho { get; set; }
        public string preco_tamanho { get; set; }
        public string forma_pagamento { get; set; }
        public Nullable<bool> retirar_pizzaria { get; set; }
        public string total { get; set; }
    }
}
