//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa_pro_chefe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dados_cliente
    {
        public int id { get; set; }
        public string cpf { get; set; }
        public string nome { get; set; }
        public int telefone { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public int cep { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
    }
}
