//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa_pro_chefe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entregador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public entregador()
        {
            this.dados_pedido = new HashSet<dados_pedido>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public int codigo { get; set; }
        public bool disponibilidade { get; set; }
        public int tipo_usuario { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dados_pedido> dados_pedido { get; set; }
        public virtual tipo_usuario tipo_usuario1 { get; set; }
    }
}
