//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa_pro_chefe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pro_chef_webEntities : DbContext
    {
        public pro_chef_webEntities()
            : base("name=pro_chef_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dados_bebida> dados_bebida { get; set; }
        public virtual DbSet<dados_cliente> dados_cliente { get; set; }
        public virtual DbSet<dados_pedido> dados_pedido { get; set; }
        public virtual DbSet<dados_pizza> dados_pizza { get; set; }
    }
}
